### PR TITLE
Use proper client key commands when using latest version (i.e. no version set)

### LINKED ISSUE #64: Version evaluating to 0.0, causing the wrong commands to run
node['chef-server'][:version].to_f is used in the recipes to determine whether or not it is running in a chef server >= 12.1. This determines which commands are run when creating users, clients, organizations. I have an issue where the --public-key is not being passed in the command so the public key is not being used. 

I'm willing to do the work to fix the issue if you can point me in the direction as to where the node['chef-server'][:version] is being set! 

logging from inside the recipe 
Chef-version: 0.0
Add client key command 'chef-server-ctl add-client-key lmid acarbone-dev /var/chef/cache/acarbone-dev.pub --key-name populator'

### PR DESCRIPTION
**Pull request by luckymike**
Fixes #64

### CODE REVIEW

**Comment by cwjohnston** [comment]
Disregarding a test which is also broken on `master`, I see a couple of failures here: 

```
  2) chef-server-populator::client when an organization is defined in the data bag when the organization is enabled adds the organziation validator key
     Failure/Error:
       expect(chef_run).to run_execute('add org validator key: nasa').with(
         :command => "chef-server-ctl add-client-key nasa nasa-validator #{Chef::Config[:file_cache_path]}/nasa.pub --key-name populator"
       )

       expected "execute[add org validator key: nasa]" to have parameters:

         command "chef-server-ctl add-client-key nasa nasa-validator /var/folders/y4/ccjrk8mn4c74ynp2lc7kpnm80000gn/T/d20160509-98497-v7v4lv/nasa.pub --key-name populator", was "chef-server-ctl add-client-key nasa nasa-validator --public-key-path /var/folders/y4/ccjrk8mn4c74ynp2lc7kpnm80000gn/T/d20160509-98497-v7v4lv/nasa.pub --key-name populator"
     # ./test/unit/client_spec.rb:102:in `block (4 levels) in <top (required)>'

  3) chef-server-populator::client a user is defined in the data bag the user is enabled the user has a client key specified sets inserts the client key as the user's populator key
     Failure/Error:
       expect(chef_run).to run_execute("set user key: #{test_user_name}").with(
         :command => "chef-server-ctl add-user-key #{test_user_name} #{test_user_pub_key_path} --key-name populator"
       )

       expected "execute[set user key: murph]" to have parameters:

         command "chef-server-ctl add-user-key murph /var/folders/y4/ccjrk8mn4c74ynp2lc7kpnm80000gn/T/d20160509-98497-1klm6fr/murph.pub --key-name populator", was "chef-server-ctl add-user-key murph --public-key-path /var/folders/y4/ccjrk8mn4c74ynp2lc7kpnm80000gn/T/d20160509-98497-1klm6fr/murph.pub --key-name populator"
     # ./test/unit/client_spec.rb:136:in `block (5 levels) in <top (required)>'
```

I think the test needs to be updated to include the `--public-key-path` flag.

**Comment by cwjohnston** [comment]
The above is giving me some "how did this work without that flag" feels; wondering if that flag is backward compatible.

**Comment by cwjohnston** [comment]
Can't effectively test in test-kitchen at the moment. May not be able to effectively test older versions going forward due to Chef's abandoning packagecloud repos (see #72).

**Comment by luckymike** [comment]
:trollface:

**Comment by luckymike** [comment]
I made these updates just prior to the packagecloud 🔫, so if the only failures relate to old versions, I'd be pro-deprecation

**Comment by cwjohnston** [comment]
The change in version dependency for chef-server cookbook is necessitated by Chef's [migration away from packagecloud.io](https://www.chef.io/blog/2016/05/02/packagecloud-repositories-disabled-please-migrate-to-packages-chef-io/).

[Per SemVer](http://semver.org/#what-should-i-do-if-i-update-my-own-dependencies-without-changing-the-public-api), I don't think we need to increment major version in our own release for this particular change.

**Pull request merged**
