### PR TITLE
Chef 12.1 client/user key fix

### PR DESCRIPTION
**Pull request by yoshiwaan**
Added fixes for add-client-key and add-user-key commands in latest chef server version

### CODE REVIEW

**Comment by luckymike** [comment]
Hi @yoshiwaan does that flag work with older versions as well, or is it only available in 12.1 and later?

**Comment by petecheslock** [comment]
@luckymike @yoshiwaan I ran into this same issue when doing a net-new build of chef `12.1.2` - The cookbook does work on `12.0.7`

Checking chef-server-ctl on 12.0.7 - it fails when trying to pass the --public-key-path flag.  I tried to see where in the changelog they added that, Also if you did set this - you'd have to set it in every location in the cookbook (i have my fork here with the changes)

https://github.com/hw-cookbooks/chef-server-populator/commit/a3b265e19b78620b93999c67bb74f92f6912e526

**Comment by yoshiwaan** [comment]
@luckymike The flag changed with the latest version of Chef Server unfortunately, so it would break backward compatibility with older versions of Chef server. Nice of Chef to change that...

I didn't realize that flag was used elsewhere in the cookbook, but I only use the server/client logic not the solo path.

**Comment by luckymike** [comment]
Rolled up in the new release. Thanks for reporting this!

**Pull request closed without merging**
