### PR TITLE
Fixes for client.rb recipe and update of readme

### PR DESCRIPTION
**Pull request by yoshiwaan**
Hi,

When using the chef-server-populator recipe using chef-client I came across the following issues:
1. There was a syntax error in one of the guards in the client recipe
2. The guards in the client recipe that check for the existence of a key didn't work because they were searching for the wrong string (I changed it so it's still backwards compatible if the string used to be different)
3. There was no documentation on the formatting of the public key.

This merge should cover all of these.

I am requesting to merge to your develop branch as I don't know the testing process you use. The changes work in my actual instance on Amazon Linux in EC2.

Thanks

### CODE REVIEW

**Comment by yoshiwaan** [comment]
I discovered there was another error in the client recipe. Users or clients would attempt to be created when looping through the data bag before the org exists. I chose the inelegant but quick solution of looping through twice, the first time to create orgs and the second to create clients and users.

**Comment by luckymike** [comment]
Thanks for raising these @yoshiwaan! I'm working on back-filling our test coverage for the client recipe, and will account for these to the extent I can. We're also going to add a CONTRIBUTING file to clarify how we prefer PRs. :)

In the meantime, could you open a new PR that has the README updates and Guard fixes only? We'll handle the version bump, and I'd like to try a more economical solution to the org/client creation issues.

**Comment by yoshiwaan** [comment]
https://github.com/hw-cookbooks/chef-server-populator/pull/11 for new pull request.

This PR can be closed.

**Comment by yoshiwaan** [comment]
Closed in favour of https://github.com/hw-cookbooks/chef-server-populator/pull/12

**Pull request closed without merging**
